# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.FloatField()),
                ('DateTime', models.DateTimeField()),
                ('Temp', models.FloatField()),
                ('FK_Pipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pipe.Pipe')),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.FloatField()),
                ('DateTime', models.DateTimeField()),
                ('Temp', models.FloatField()),
                ('FK_Pipe_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pipe.Pipe')),
            ],
        ),
    ]
