# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
